model_path: "EleutherAI/pythia-125m-deduped"
tokenizer_path: "EleutherAI/gpt-neox-20b"
save_dir: "/fsx/dakota/ckpts/pythia/125M-sft"

train_args:
  output_dir: "/fsx/dakota/ckpts/pythia/125M-sft"
  num_train_epochs: 1
  logging_steps: 100
  save_strategy: "epoch"
  per_device_train_batch_size: 1
  per_device_eval_batch_size: 1
  warmup_steps: 100
  weight_decay: 0.01
  learning_rate: 1.0e-4
  save_total_limit: 1
  logging_dir: "./logs"
  fp16: True
  evaluation_strategy: "epoch"

data_path: "CarperAI/openai_summarize_tldr"